import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { walletSnapshotSchema } from "./mcp/schema.js";
import { compareWalletSnapshots, getWalletChanges, getWalletReport } from "./mcp/changes.js";
import type { AppConfig } from "./types.js";

export async function testAssetHistory(value: unknown, cfg: AppConfig) {
  const base = walletSnapshotSchema.parse(value);
  assert.ok(base.assets);
  const advance = (source = base, number = "124") => {
    const result = structuredClone(source);
    for (const part of [result, result.protocol, result.voting, result.rewards, result.assets]) if (part) part.observation.blockNumber = number;
    return result;
  };
  const legacy = structuredClone(base); delete legacy.assets;
  const initialized = compareWalletSnapshots(legacy, advance());
  assert.deepEqual(initialized.initializedSections, ["balances", "locks"]);
  assert.equal(initialized.changes.length, 0, "New coverage is not an apparent deposit");
  assert.equal(initialized.findings.filter(row => row.code === "SECTION_BASELINE_CREATED").length, 2);
  assert.equal(compareWalletSnapshots(base, advance()).changes.length, 0);
  const changed = advance();
  changed.assets!.liquidBalances[0].amountRaw = "900719925474099312345";
  changed.assets!.locks[0].principalRaw = "101000000000000000000";
  changed.assets!.locks[0].permanent = true;
  changed.assets!.locks[0].unlockAt = null;
  const report = compareWalletSnapshots(base, changed);
  const balance = report.changes.find(row => row.section === "balances")!;
  assert.equal(balance.deltaRaw, (900719925474099312345n - BigInt(base.assets!.liquidBalances[0].amountRaw!)).toString());
  assert.equal(report.findings.find(row => row.code === "LOCK_CHANGED" && row.key?.endsWith("principalRaw"))?.deltaFormatted, "1");
  assert.ok(report.changes.some(row => row.key.endsWith("/permanent")));
  const partial = advance();
  partial.status = "PARTIAL_BOUNDED_SCOPE";
  partial.assets!.balancesStatus = "PARTIAL_BOUNDED_SCOPE";
  partial.assets!.liquidBalances[0].status = "READ_FAILED";
  partial.assets!.liquidBalances[0].amountRaw = null;
  const partialReport = compareWalletSnapshots(base, partial);
  assert.equal(partialReport.status, "PARTIAL");
  assert.deepEqual(partialReport.unavailableSections, ["balances"]);
  assert.equal(partialReport.changes.filter(row => row.section === "balances").length, 0);
  const lockPartial = advance(changed);
  lockPartial.status = "PARTIAL_BOUNDED_SCOPE";
  lockPartial.assets!.locksStatus = "PARTIAL_BOUNDED_SCOPE";
  Object.assign(lockPartial.assets!.locks[0], { status: "READ_FAILED", principalRaw: null });
  const isolated = compareWalletSnapshots(base, lockPartial);
  assert.deepEqual(isolated.unavailableSections, ["locks"]);
  assert.ok(isolated.changes.some(row => row.section === "balances"));
  assert.equal(isolated.changes.some(row => row.section === "locks"), false);
  const unitsChanged = advance(changed);
  unitsChanged.assets!.liquidBalances[0].decimals = 6;
  assert.equal(compareWalletSnapshots(base, unitsChanged).findings.find(row => row.section === "balances")?.deltaFormatted, null);
  const tokenChanged = advance(changed);
  tokenChanged.assets!.locks[0].token = "0x0000000000000000000000000000000000000098";
  assert.equal(compareWalletSnapshots(base, tokenChanged).changes.find(row => row.key.endsWith("principalRaw"))?.deltaRaw, null);
  const notOwned = advance();
  Object.assign(notOwned.assets!.locks[0], { status: "NOT_OWNED", owner: "0x0000000000000000000000000000000000000099", principalRaw: null, decimals: null, decimalsSource: "UNKNOWN", permanent: null, unlockAt: null });
  const gone = compareWalletSnapshots(base, notOwned);
  assert.equal(gone.changes.find(row => row.key.endsWith("principalRaw"))?.deltaRaw, null);
  const bad = advance(); bad.assets!.observation.blockNumber = "999";
  assert.throws(() => compareWalletSnapshots(base, bad), /asset snapshot identity/);
  const duplicate = advance(); duplicate.assets!.liquidBalances.push(duplicate.assets!.liquidBalances[0]);
  assert.throws(() => compareWalletSnapshots(base, duplicate));
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "aero-asset-history-"));
  const runtime = { cfg, client: {} };
  const capture = (snapshot: unknown, id = randomUUID()) => getWalletChanges(runtime, directory, async () => snapshot, { requestId: id });
  try {
    const oldId = randomUUID(); await capture(legacy, oldId);
    const file = path.join(directory, fs.readdirSync(directory).find(name => name.endsWith(".json"))!);
    const oldStore = JSON.parse(fs.readFileSync(file, "utf8"));
    oldStore.version = 2; delete oldStore.reports[0].initializedSections;
    fs.writeFileSync(file, JSON.stringify(oldStore));
    const originalBody = fs.readFileSync(file, "utf8");
    assert.deepEqual(await getWalletReport({ reportId: oldId }, runtime, directory), oldStore.reports[0]);
    assert.equal(fs.readFileSync(file, "utf8"), originalBody);
    const id = randomUUID(); const upgrade = await capture(advance(), id);
    assert.deepEqual(upgrade.initializedSections, ["balances", "locks"]);
    const store = JSON.parse(fs.readFileSync(file, "utf8"));
    assert.equal(store.version, 3);
    assert.deepEqual(store.reports[0], oldStore.reports[0]);
    assert.deepEqual(await getWalletChanges(runtime, directory, async () => { throw new Error("Replay must not read RPC"); }, { requestId: id }), upgrade);
    const beforePartial = JSON.stringify(store.snapshot);
    await capture(advance(partial, "125"));
    assert.equal(JSON.stringify(JSON.parse(fs.readFileSync(file, "utf8")).snapshot), beforePartial);
    const later = advance(changed, "126");
    const next = await capture(later);
    assert.equal(next.previousObservation?.blockNumber, "124");
    assert.ok(next.changes.some(row => row.section === "balances"));
    assert.deepEqual(await getWalletReport({ reportId: oldId }, runtime, directory), oldStore.reports[0]);
    await assert.rejects(capture(advance(legacy, "127")), /asset coverage regressed/);
  } finally { fs.rmSync(directory, { recursive: true, force: true }); }
}
